controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#COUNTRIES
countries_list:
    path: /api/countries
    controller: App\Controller\CountryController::indexAction
    methods: [GET]

country_show:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::showAction
    methods: [GET]
    requirements:
        countryId: '\d+'

country_create:
    path: /api/countries
    controller: App\Controller\CountryController::createAction
    methods: [POST]

country_update:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::updateAction
    methods: [PUT]
    requirements:
        countryId: '\d+'

country_delete:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::deleteAction
    methods: [DELETE]
    requirements:
        countryId: '\d+'

#CITIES
cities_list:
    path: /api/cities
    controller: App\Controller\CityController::indexAction
    methods: [GET]

city_show:
    path: /api/cities/{cityId}
    controller: App\Controller\CityController::showAction
    methods: [GET]
    requirements:
        cityId: '\d+'

city_create:
    path: /api/cities
    controller: App\Controller\CityController::createAction
    methods: [POST]

city_update:
    path: /api/cities/{cityId}
    controller: App\Controller\CityController::updateAction
    methods: [PUT]
    requirements:
        cityId: '\d+'

city_delete:
    path: /api/cities/{cityId}
    controller: App\Controller\CityController::deleteAction
    methods: [DELETE]
    requirements:
        cityId: '\d+'
