controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

countries_list:
    path: /api/countries
    controller: App\Controller\CountryController::indexAction
    methods: [GET]

country_show:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::showAction
    methods: [GET]
    requirements:
        countryId: '\d+'

country_create:
    path: /api/countries
    controller: App\Controller\CountryController::createAction
    methods: [POST]

country_update:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::updateAction
    methods: [PUT]
    requirements:
        countryId: '\d+'

country_delete:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::deleteAction
    methods: [DELETE]
    requirements:
        countryId: '\d+'

