controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#==========USER==========
#login to get jwt token
api_login_check:
    path: /api/login_check

#register new user
api_register:
    path: /api/register
    controller: App\Controller\RegistrationController::register
    methods: [POST]

#get user's related clients
user_clients_list:
    path: /api/user/clients
    controller: App\Controller\UserController::indexAction
    methods: [GET]

#get user's specific client
user_clients_show:
    path: /api/user/clients/{clientId}
    controller: App\Controller\UserController::showAction
    methods: [GET]
    requirements:
        clientId: '\d+'

#create new client by the logged in user
user_clients_create:
    path: /api/user/clients
    controller: App\Controller\UserController::createAction
    methods: [POST]

#update user's client
user_clients_update:
    path: /api/user/clients/{clientId}
    controller: App\Controller\UserController::updateAction
    methods: [PUT]
    requirements:
        clientId: '\d+'

#delete user's client
user_clients_delete:
    path: /api/user/clients/{clientId}
    controller: App\Controller\UserController::deleteAction
    methods: [DELETE]
    requirements:
        clientId: '\d+'

#==========COUNTRIES==========
#get list of all countries
countries_list:
    path: /api/countries
    controller: App\Controller\CountryController::indexAction
    methods: [GET]

#get one country provided by id
country_show:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::showAction
    methods: [GET]
    requirements:
        countryId: '\d+'

#create new country
country_create:
    path: /api/countries
    controller: App\Controller\CountryController::createAction
    methods: [POST]

#update country
country_update:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::updateAction
    methods: [PUT]
    requirements:
        countryId: '\d+'

#delete country
country_delete:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::deleteAction
    methods: [DELETE]
    requirements:
        countryId: '\d+'

#==========CITIES==========
#get list of all cities
cities_list:
    path: /api/cities
    controller: App\Controller\CityController::indexAction
    methods: [GET]

#get one city provided by id
city_show:
    path: /api/cities/{cityId}
    controller: App\Controller\CityController::showAction
    methods: [GET]
    requirements:
        cityId: '\d+'

#create new city
city_create:
    path: /api/cities
    controller: App\Controller\CityController::createAction
    methods: [POST]

#update city
city_update:
    path: /api/cities/{cityId}
    controller: App\Controller\CityController::updateAction
    methods: [PUT]
    requirements:
        cityId: '\d+'

#delete city
city_delete:
    path: /api/cities/{cityId}
    controller: App\Controller\CityController::deleteAction
    methods: [DELETE]
    requirements:
        cityId: '\d+'

#==========CONTACTS==========
#get list of all contacts
contacts_list:
    path: /api/contacts
    controller: App\Controller\ContactController::indexAction
    methods: [GET]

#get one contact provided by id
contact_show:
    path: /api/contacts/{contactId}
    controller: App\Controller\ContactController::showAction
    methods: [GET]
    requirements:
        contactId: '\d+'

#create new contact
contact_create:
    path: /api/contacts
    controller: App\Controller\ContactController::createAction
    methods: [POST]

#update contact
contact_update:
    path: /api/contacts/{contactId}
    controller: App\Controller\ContactController::updateAction
    methods: [PUT]
    requirements:
        contactId: '\d+'

#delete contact
contact_delete:
    path: /api/contacts/{contactId}
    controller: App\Controller\ContactController::deleteAction
    methods: [DELETE]
    requirements:
        contactId: '\d+'

#==========ADDRESSES==========
#get list of all addresses
addresses_list:
    path: /api/addresses
    controller: App\Controller\AddressController::indexAction
    methods: [GET]

#get one address provided by id
address_show:
    path: /api/addresses/{addressId}
    controller: App\Controller\AddressController::showAction
    methods: [GET]
    requirements:
        addressId: '\d+'

#create new address
address_create:
    path: /api/addresses
    controller: App\Controller\AddressController::createAction
    methods: [POST]

#update address
address_update:
    path: /api/addresses/{addressId}
    controller: App\Controller\AddressController::updateAction
    methods: [PUT]
    requirements:
        addressId: '\d+'

#delete address
address_delete:
    path: /api/addresses/{addressId}
    controller: App\Controller\AddressController::deleteAction
    methods: [DELETE]
    requirements:
        addressId: '\d+'

#==========CLIENTS=========
#get list of all clients
clients_list:
    path: /api/clients
    controller: App\Controller\ClientController::indexAction
    methods: [GET]

#get one client provided by id
client_show:
    path: /api/clients/{clientId}
    controller: App\Controller\ClientController::showAction
    methods: [GET]
    requirements:
        clientId: '\d+'

#create new client
client_create:
    path: /api/clients
    controller: App\Controller\ClientController::createAction
    methods: [POST]

#update client
client_update:
    path: /api/clients/{clientId}
    controller: App\Controller\ClientController::updateAction
    methods: [PUT]
    requirements:
        clientId: '\d+'

#delete client
client_delete:
    path: /api/clients/{clientId}
    controller: App\Controller\ClientController::deleteAction
    methods: [DELETE]
    requirements:
        clientId: '\d+'




