controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#USER
api_login_check:
    path: /api/login_check

api_register:
    path: /api/register
    controller: App\Controller\RegistrationController::register
    methods: [POST]

user_clients_list:
    path: /api/user/{userId}/clients
    controller: App\Controller\UserController::indexAction
    methods: [GET]
    requirements:
        userId: '\d+'

#COUNTRIES
countries_list:
    path: /api/countries
    controller: App\Controller\CountryController::indexAction
    methods: [GET]

country_show:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::showAction
    methods: [GET]
    requirements:
        countryId: '\d+'

country_create:
    path: /api/countries
    controller: App\Controller\CountryController::createAction
    methods: [POST]

country_update:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::updateAction
    methods: [PUT]
    requirements:
        countryId: '\d+'

country_delete:
    path: /api/countries/{countryId}
    controller: App\Controller\CountryController::deleteAction
    methods: [DELETE]
    requirements:
        countryId: '\d+'

#CITIES
cities_list:
    path: /api/cities
    controller: App\Controller\CityController::indexAction
    methods: [GET]

city_show:
    path: /api/cities/{cityId}
    controller: App\Controller\CityController::showAction
    methods: [GET]
    requirements:
        cityId: '\d+'

city_create:
    path: /api/cities
    controller: App\Controller\CityController::createAction
    methods: [POST]

city_update:
    path: /api/cities/{cityId}
    controller: App\Controller\CityController::updateAction
    methods: [PUT]
    requirements:
        cityId: '\d+'

city_delete:
    path: /api/cities/{cityId}
    controller: App\Controller\CityController::deleteAction
    methods: [DELETE]
    requirements:
        cityId: '\d+'

#CONTACTS
contacts_list:
    path: /api/contacts
    controller: App\Controller\ContactController::indexAction
    methods: [GET]

contact_show:
    path: /api/contacts/{contactId}
    controller: App\Controller\ContactController::showAction
    methods: [GET]
    requirements:
        contactId: '\d+'

contact_create:
    path: /api/contacts
    controller: App\Controller\ContactController::createAction
    methods: [POST]

contact_update:
    path: /api/contacts/{contactId}
    controller: App\Controller\ContactController::updateAction
    methods: [PUT]
    requirements:
        contactId: '\d+'

contact_delete:
    path: /api/contacts/{contactId}
    controller: App\Controller\ContactController::deleteAction
    methods: [DELETE]
    requirements:
        contactId: '\d+'

#ADDRESSES
addresses_list:
    path: /api/addresses
    controller: App\Controller\AddressController::indexAction
    methods: [GET]

address_show:
    path: /api/addresses/{addressId}
    controller: App\Controller\AddressController::showAction
    methods: [GET]
    requirements:
        addressId: '\d+'

address_create:
    path: /api/addresses
    controller: App\Controller\AddressController::createAction
    methods: [POST]

address_update:
    path: /api/addresses/{addressId}
    controller: App\Controller\AddressController::updateAction
    methods: [PUT]
    requirements:
        addressId: '\d+'

address_delete:
    path: /api/addresses/{addressId}
    controller: App\Controller\AddressController::deleteAction
    methods: [DELETE]
    requirements:
        addressId: '\d+'

#CLIENTS

clients_list:
    path: /api/clients
    controller: App\Controller\ClientController::indexAction
    methods: [GET]

client_show:
    path: /api/clients/{clientId}
    controller: App\Controller\ClientController::showAction
    methods: [GET]
    requirements:
        clientId: '\d+'

client_create:
    path: /api/clients
    controller: App\Controller\ClientController::createAction
    methods: [POST]

client_update:
    path: /api/clients/{clientId}
    controller: App\Controller\ClientController::updateAction
    methods: [PUT]
    requirements:
        clientId: '\d+'

client_delete:
    path: /api/clients/{clientId}
    controller: App\Controller\ClientController::deleteAction
    methods: [DELETE]
    requirements:
        clientId: '\d+'




